networks:
  opensearch-net:
    external: true
    name: opensearch-net

services:
  opens1:
    image: opensearchproject/opensearch:3.4.0
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opens1
      - discovery.seed_hosts=opens1,opens2,opens3
      - cluster.initial_master_nodes=opens1,opens2,opens3
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    volumes:
      - /srv/opensearch/data/b1:/usr/share/opensearch/data
    ports:
      - target: 9200
        published: 9200
        mode: host
      - target: 9600
        published: 9600
        mode: host
    networks:
      - opensearch-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.role == b1
      restart_policy:
        condition: on-failure

  opens2:
    image: opensearchproject/opensearch:3.4.0
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opens2
      - discovery.seed_hosts=opens1,opens2,opens3
      - cluster.initial_master_nodes=opens1,opens2,opens3
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    volumes:
      - /srv/opensearch/data/b2:/usr/share/opensearch/data
    ports:
      - target: 9200
        published: 9200
        mode: host
      - target: 9600
        published: 9600
        mode: host
    networks:
      - opensearch-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.role == b2
      restart_policy:
        condition: on-failure

  opens3:
    image: opensearchproject/opensearch:3.4.0
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opens3
      - discovery.seed_hosts=opens1,opens2,opens3
      - cluster.initial_master_nodes=opens1,opens2,opens3
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    volumes:
      - /srv/opensearch/data/b3:/usr/share/opensearch/data
    ports:
      - target: 9200
        published: 9200
        mode: host
      - target: 9600
        published: 9600
        mode: host
    networks:
      - opensearch-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.role == b3
      restart_policy:
        condition: on-failure
